overwrite: true
schema: 'https://fakeql.com/graphql/4f25a174ecbddf03ebb05e5ddb88ee9a'
documents: 'src/**/*.gql'
generates:
  src/generated/index.ts:
    plugins:
      - add:
          content: '// @ts-nocheck'
      - typescript
      - typescript-operations
      - typescript-react-query
      - typescript-msw
    config:
      fetcher:
        endpoint: 'https://fakeql.com/graphql/4f25a174ecbddf03ebb05e5ddb88ee9a'
        fetchParams:
          headers:
            # MSW does not intercept unless this header is explicitly specified
            Content-Type: 'application/json'
      addInfiniteQuery: true
  ./graphql.schema.json:
    plugins:
      - introspection
