query Todos($page: Int, $limit: Int, $input: TodosWhere, $sort: String, $direction: String) {
  todos(page: $page, limit: $limit, where: $input, sort: $sort, dir: $direction) {
    id
    task
    done
  }
}
