import { readFile } from 'fs/promises';

const injectTailwindCss = async (): Promise<void> => {
  try {
    const twStyle = document.createElement('style');
    twStyle.id = 'tailwind-style';
    // generated by pretest script (package.json)
    twStyle.innerHTML = await readFile('./src/generated/output.css', 'utf-8');
    document.head.appendChild(twStyle);
  } catch (e) {
    // eslint-disable-next-line no-console
    console.error(e);
  }
};

export { injectTailwindCss };
